app/urls.py
from django.urls import path

from .views import (autenticacao_views, cliente_views, consulta_views,
                    funcionario_views, pet_views)

urlpatterns = [
    path('cadastrar_cliente', cliente_views.cadastrar_cliente,
         name='cadastrar_cliente'),
    path('listar_clientes', cliente_views.listar_clientes, name='listar_clientes'),
    path('lista_cliente/<int:id>', cliente_views.listar_cliente_id,
         name='listar_cliente_id'),
    path('editar_cliente/<int:id>',
         cliente_views.editar_cliente, name='editar_cliente'),
    path('remover_cliente/<int:id>',
         cliente_views.remover_cliente, name='remover_cliente'),
    path('cadastrar_pet/<int:id>', pet_views.inserir_pet, name='cadastrar_pet'),
    path('listar_pet/<int:id>', pet_views.listar_pet_id, name='listar_pet_id'),
    path('cadastrar_consulta/<int:id>',
         consulta_views.inserir_consulta, name='cadastrar_consulta'),
    path('lista_consulta/<int:id>', consulta_views.listar_consulta_id,
         name='listar_consulta_id'),
    path('cadastrar_funcionario', funcionario_views.inserir_funcionario,
         name='cadastrar_funcionario'),
    path('listar_funcionarios', funcionario_views.listar_funcionarios,
         name='listar_funcionarios'),
    path('login', autenticacao_views.login_usuario, name='login'),
    path('logout', autenticacao_views.deslogar_usuario, name='logout'),
    path('enviar_consulta/<int:id>',
         consulta_views.enviar_email_consulta, name='enviar_consulta'),
]

gerenciamento_pet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_localflavor_br.br_states import STATE_CHOICES

# Create your models here.


class EnderecoCliente(models.Model):
    rua = models.CharField(max_length=50, null=False, blank=False)
    cidade = models.CharField(max_length=30, null=False, blank=False)
    estado = models.CharField(
        max_length=2, choices=STATE_CHOICES, null=False, blank=False)


class Cliente(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    endereco = models.ForeignKey(EnderecoCliente, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=14, null=False, blank=False)
    data_nascimento = models.DateField(null=False, blank=False)
    profissao = models.CharField(max_length=25, null=False, blank=False)


class Pet(models.Model):
    CATEGORIA_PET_CHOICES = (
        ('Ca', 'Cachorro'),
        ('Ga', 'Gato'),
        ('Co', 'Coelho'),
    )

    COR_PET_CHOICES = (
        ('Pr', 'Preto'),
        ('Br', 'Branco'),
        ('Ci', 'Cinza'),
        ('Ma', 'Marrom'),
    )
    nome = models.CharField(max_length=50, null=False, blank=False)
    nascimento = models.DateField(null=False, blank=False)
    categoria = models.CharField(
        max_length=2, choices=CATEGORIA_PET_CHOICES, null=False, blank=False)
    cor = models.CharField(
        max_length=2, choices=COR_PET_CHOICES, null=False, blank=False)
    dono = models.ForeignKey(
        Cliente, on_delete=models.CASCADE, null=False, blank=False)


class ConsultaPet(models.Model):
    pet = models.ForeignKey(
        Pet, on_delete=models.CASCADE, null=False, blank=False)
    data = models.DateField(null=False, blank=False, auto_now_add=True)
    motivo_consulta = models.CharField(max_length=200, null=False, blank=False)
    peso_atual = models.FloatField(null=False, blank=False)
    medicamento_atual = models.TextField(null=False, blank=True)
    medicamentos_prescritos = models.TextField(null=False, blank=True)
    exames_prescritos = models.TextField(null=False, blank=True)


class Funcionario(AbstractUser):
    CARGO_CHOICES = [
        (1, 'Veterinario'),
        (2, 'Financeiro'),
        (3, 'Atendimento'),
    ]
    nome = models.CharField(max_length=50, null=False, blank=False)
    nascimento = models.DateField(null=False, blank=False)
    cargo = models.IntegerField(choices=CARGO_CHOICES, null=False, blank=False)

app/forms/cliente_forms.py
from django import forms
from django.forms import TextInput, DateInput

from ..models import Cliente


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'email', 'data_nascimento', 'cpf', 'profissao']
        widgets = {
            'data_nascimento': DateInput(
                attrs={'type': "date"}
            )
        }

app/views/cliente_views.py
import datetime

from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import redirect, render

from ..entidades import cliente, endereco
from ..forms.cliente_forms import ClienteForm
from ..forms.endereco_forms import EnderecoClienteForm
from ..services import (cliente_service, consulta_service, endereco_service,
                        pet_service)


@login_required()
def listar_clientes(request):
    clientes = cliente_service.listar_clientes()
    return render(request, 'clientes/lista_clientes.html', {'clientes': clientes})


@login_required()
def listar_cliente_id(request, id):
    cliente = cliente_service.listar_cliente_id(id)
    pets = pet_service.listar_pets(id)
    consultas = consulta_service.listar_consultas_pets(id)
    return render(request, 'clientes/lista_cliente.html', {'cliente': cliente, 'pets': pets, 'consultas': consultas})


@user_passes_test(lambda u: u.cargo == 2)
def remover_cliente(request, id):
    cliente = cliente_service.listar_cliente_id(id)
    endereco = endereco_service.listar_endereco_id(cliente.endereco.id)
    if request.method == "POST":
        cliente_service.remover_cliente(cliente)
        endereco_service.remover_endereco(endereco)
        return redirect('listar_clientes')
    return render(request, 'clientes/confirma_exclusao.html', {'cliente': cliente})


@login_required()
def cadastrar_cliente(request):
    if request.method == "POST":
        form_cliente = ClienteForm(request.POST)
        form_endereco = EnderecoClienteForm(request.POST)
        if form_cliente.is_valid():
            nome = form_cliente.cleaned_data["nome"]
            email = form_cliente.cleaned_data["email"]
            cpf = form_cliente.cleaned_data["cpf"]
            data_nascimento = form_cliente.cleaned_data["data_nascimento"]
            profissao = form_cliente.cleaned_data["profissao"]
            if form_endereco.is_valid():
                rua = form_endereco.cleaned_data["rua"]
                cidade = form_endereco.cleaned_data["cidade"]
                estado = form_endereco.cleaned_data["estado"]
                endereco_novo = endereco.Endereco(
                    rua=rua, cidade=cidade, estado=estado)
                endereco_bd = endereco_service.cadastrar_endereco(
                    endereco_novo)
                cliente_novo = cliente.Cliente(nome=nome, email=email, data_nascimento=data_nascimento,
                                               profissao=profissao, cpf=cpf, endereco=endereco_bd)
                cliente_service.cadastrar_cliente(cliente_novo)
                return redirect('listar_clientes')
    else:
        form_cliente = ClienteForm()
        form_endereco = EnderecoClienteForm()
    return render(request, 'clientes/form_cliente.html', {'form_cliente': form_cliente, 'form_endereco': form_endereco})


@user_passes_test(lambda u: u.cargo == 1)
def editar_cliente(request, id):
    cliente_editar = cliente_service.listar_cliente_id(id)
    cliente_editar.data_nascimento = cliente_editar.data_nascimento.strftime(
        '%Y-%m-%d')
    form_cliente = ClienteForm(request.POST or None, instance=cliente_editar)
    endereco_editar = endereco_service.listar_endereco_id(
        cliente_editar.endereco.id)
    form_endereco = EnderecoClienteForm(
        request.POST or None, instance=endereco_editar)
    if form_cliente.is_valid():
        nome = form_cliente.cleaned_data["nome"]
        email = form_cliente.cleaned_data["email"]
        cpf = form_cliente.cleaned_data["cpf"]
        data_nascimento = form_cliente.cleaned_data["data_nascimento"]
        profissao = form_cliente.cleaned_data["profissao"]
        if form_endereco.is_valid():
            rua = form_endereco.cleaned_data["rua"]
            cidade = form_endereco.cleaned_data["cidade"]
            estado = form_endereco.cleaned_data["estado"]
            endereco_novo = endereco.Endereco(
                rua=rua, cidade=cidade, estado=estado)
            endereco_editado = endereco_service.editar_endereco(
                endereco_editar, endereco_novo)
            cliente_novo = cliente.Cliente(nome=nome, email=email, data_nascimento=data_nascimento,
                                           profissao=profissao, cpf=cpf, endereco=endereco_editado)
            cliente_service.editar_cliente(cliente_editar, cliente_novo)
            return redirect('listar_clientes')
    return render(request, 'clientes/form_cliente.html', {'form_cliente': form_cliente, 'form_endereco': form_endereco})

app/templates/clientes/confirma_exclusao.html
{% extends 'base.html' %}

{% block title %}
Remoção de clientes
{% endblock title %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Tem certeza que deseja remover o cliente abaixo?</h3>
    </div>
    <div class="box-body">
        <h5>Nome: {{cliente.nome}}</h5>
        <h5>Profissão: {{cliente.profissao}}</h5>
        <h5>Data de Nascimento: {{cliente.data_nascimento}}</h5>
        <h5>Email: {{cliente.email}}</h5>
        <h5>CPF: {{cliente.cpf}}</h5>

        <form method="POST">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Remover</button>
        </form>
    </div>
</div>


{% endblock content %}

app/templates/clientes/form_cliente.html
{% extends 'base.html' %}

{% load meus_filtros %}

{% block title %}
Cadastro de clientes
{% endblock title %}

{% block content %}
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Cadastro de clientes</h3>
        </div>
        <div class="box-body">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{form_cliente.nome.errors}}
                    <label>Nome: </label>
                    {{form_cliente.nome|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_cliente.data_nascimento.errors}}
                    <label>Data de nascimento: </label>
                    {{form_cliente.data_nascimento|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_cliente.email.errors}}
                    <label>Email: </label>
                    {{form_cliente.email|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    <label>CPF: </label>
                    {{form_cliente.cpf|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_cliente.profissao.errors}}
                    <label>Profissão: </label>
                    {{form_cliente.profissao|addclass:'form-control'}}
                </div>
                <hr>
                <h4>Endereço</h4>
                <div class="form-group">
                    {{form_endereco.rua.errors}}
                    <label>Rua: </label>
                    {{form_endereco.rua|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_endereco.cidade.errors}}
                    <label>Cidade: </label>
                    {{form_endereco.cidade|addclass:'form-control'}}
                </div>
                <div class="form-group">
                    {{form_endereco.estado.errors}}
                    <label>Estado: </label>
                    {{form_endereco.estado|addclass:'form-control'}}
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-primary" name="Cadastrar">
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

app/templates/clientes/lista_cliente.html
{% extends 'base.html' %}

{% block title %}
Listagem de cliente
{% endblock title %}

{% block content %}
<section class="content">
      <div class="row">
        <div class="col-md-3">
          <!-- Profile Image -->
          <div class="box box-primary">
            <div class="box-body box-profile">
              <h3 class="profile-username text-center">{{cliente.nome}}</h3>

              <p class="text-muted text-center">{{cliente.profissao}}</p>

              <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>Nascimento</b> <a class="pull-right">{{cliente.data_nascimento}}</a>
                </li>
                <li class="list-group-item">
                  <b>CPF</b> <a class="pull-right">{{cliente.cpf}}</a>
                </li>
              </ul>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
          <!-- About Me Box -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Pets</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              {% for pet in pets %}
              <a href="{% url 'listar_pet_id' pet.id %}">
                <strong><i class="fa fa-paw margin-r-5"></i> {{pet.nome}}</strong>
              </a>

              <p class="text-muted">
                {{pet.get_categoria_display}} - {{pet.get_cor_display}}
              </p>
              <hr>
              {% endfor %}
              <div class="row">
                <div class="col-md-12">
                  <a href="{% url 'cadastrar_pet' cliente.id %}" class="btn btn-primary btn-block">Cadastrar Pet</a>
                </div>
              </div>

            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#timeline" data-toggle="tab">Histórico</a></li>
                </ul>
                <div class="tab-content">
                    <div class="active tab-pane" id="timeline">
                        <ul class="timeline timeline-inverse">
                            <li class="time-label">
                        <span class="bg-red">
                          {% now "SHORT_DATE_FORMAT" %}
                        </span>
                            </li>

                            {% for consulta in consultas %}
                            <li>
                                <i class="fa fa-paw bg-blue"></i>
                                <div class="timeline-item">
                                    <span class="time"> <i class="fa fa-calendar"></i>
                                        {{consulta.data}}
                                    </span>
                                    <h3 class="timeline-header">
                                        {{consulta.pet.nome}} realizou nova consulta
                                    </h3>
                                    <div class="timeline-body">
                                        {{consulta.motivo_consulta}}
                                    </div>
                                    <div class="timeline-footer">
                                      <a class="btn btn-primary btn-xs" href="{% url 'listar_consulta_id' consulta.id %}">
                                        Visualizar consulta
                                      </a>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}

                            <!-- END timeline item -->

                            <li>
                                <i class="fa fa-clock-o bg-gray"></i>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

    </section>
{% endblock content %}

app/templates/clientes/lista_clientes.html
{% extends 'base.html' %}

{% block title %}
Listagem de clientes
{% endblock title %}

{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Listagem de clientes</h3>
    </div>

    <div class="box-body">
        <table class="table">
            <thead>
               <tr>
                   <th>Nome</th>
                   <th>Data de Nascimento</th>
                   <th>Profissão</th>
                   <th>Ações</th>
               </tr>
            </thead>
            <tbody>
                {% for cliente in clientes %}
                <tr>
                    <td><a href="{% url 'listar_cliente_id' cliente.id %}">{{cliente.nome}}</a></td>
                    <td>{{cliente.data_nascimento}}</td>
                    <td>{{cliente.profissao}}</td>
                    <td>
                        <a href="{% url 'editar_cliente' cliente.id %}">Editar</a>
                        <a href="{% url 'remover_cliente' cliente.id %}">Remover</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <hr>
        <a href="{% url 'cadastrar_cliente' %}">
            <button class="btn btn-primary">Cadastrar</button>
        </a>
    </div>
</div>
{% endblock content %}