app/urls.py
from django.urls import path

from .views import (autenticacao_views, cliente_views, consulta_views,
                    funcionario_views, pet_views)

urlpatterns = [
    path('cadastrar_cliente', cliente_views.cadastrar_cliente,
         name='cadastrar_cliente'),
    path('listar_clientes', cliente_views.listar_clientes, name='listar_clientes'),
    path('lista_cliente/<int:id>', cliente_views.listar_cliente_id,
         name='listar_cliente_id'),
    path('editar_cliente/<int:id>',
         cliente_views.editar_cliente, name='editar_cliente'),
    path('remover_cliente/<int:id>',
         cliente_views.remover_cliente, name='remover_cliente'),
    path('cadastrar_pet/<int:id>', pet_views.inserir_pet, name='cadastrar_pet'),
    path('listar_pet/<int:id>', pet_views.listar_pet_id, name='listar_pet_id'),
    path('cadastrar_consulta/<int:id>',
         consulta_views.inserir_consulta, name='cadastrar_consulta'),
    path('lista_consulta/<int:id>', consulta_views.listar_consulta_id,
         name='listar_consulta_id'),
    path('cadastrar_funcionario', funcionario_views.inserir_funcionario,
         name='cadastrar_funcionario'),
    path('listar_funcionarios', funcionario_views.listar_funcionarios,
         name='listar_funcionarios'),
    path('login', autenticacao_views.login_usuario, name='login'),
    path('logout', autenticacao_views.deslogar_usuario, name='logout'),
    path('enviar_consulta/<int:id>',
         consulta_views.enviar_email_consulta, name='enviar_consulta'),
]

gerenciamento_pet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_localflavor_br.br_states import STATE_CHOICES

# Create your models here.


class EnderecoCliente(models.Model):
    rua = models.CharField(max_length=50, null=False, blank=False)
    cidade = models.CharField(max_length=30, null=False, blank=False)
    estado = models.CharField(
        max_length=2, choices=STATE_CHOICES, null=False, blank=False)


class Cliente(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    endereco = models.ForeignKey(EnderecoCliente, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=14, null=False, blank=False)
    data_nascimento = models.DateField(null=False, blank=False)
    profissao = models.CharField(max_length=25, null=False, blank=False)


class Pet(models.Model):
    CATEGORIA_PET_CHOICES = (
        ('Ca', 'Cachorro'),
        ('Ga', 'Gato'),
        ('Co', 'Coelho'),
    )

    COR_PET_CHOICES = (
        ('Pr', 'Preto'),
        ('Br', 'Branco'),
        ('Ci', 'Cinza'),
        ('Ma', 'Marrom'),
    )
    nome = models.CharField(max_length=50, null=False, blank=False)
    nascimento = models.DateField(null=False, blank=False)
    categoria = models.CharField(
        max_length=2, choices=CATEGORIA_PET_CHOICES, null=False, blank=False)
    cor = models.CharField(
        max_length=2, choices=COR_PET_CHOICES, null=False, blank=False)
    dono = models.ForeignKey(
        Cliente, on_delete=models.CASCADE, null=False, blank=False)


class ConsultaPet(models.Model):
    pet = models.ForeignKey(
        Pet, on_delete=models.CASCADE, null=False, blank=False)
    data = models.DateField(null=False, blank=False, auto_now_add=True)
    motivo_consulta = models.CharField(max_length=200, null=False, blank=False)
    peso_atual = models.FloatField(null=False, blank=False)
    medicamento_atual = models.TextField(null=False, blank=True)
    medicamentos_prescritos = models.TextField(null=False, blank=True)
    exames_prescritos = models.TextField(null=False, blank=True)


class Funcionario(AbstractUser):
    CARGO_CHOICES = [
        (1, 'Veterinario'),
        (2, 'Financeiro'),
        (3, 'Atendimento'),
    ]
    nome = models.CharField(max_length=50, null=False, blank=False)
    nascimento = models.DateField(null=False, blank=False)
    cargo = models.IntegerField(choices=CARGO_CHOICES, null=False, blank=False)

app/forms/funcionario_forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import DateInput

from ..models import Funcionario


class FuncionarioForm(UserCreationForm):
    class Meta:
        model = Funcionario
        fields = UserCreationForm.Meta.fields + ('nome', 'nascimento', 'cargo')
        widgets = {
            'nascimento': DateInput(
                attrs={'type': "date"}
            )
        }

app/views/funcionario_views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password
from django.shortcuts import redirect, render

from ..entidades import funcionario
from ..forms.funcionario_forms import FuncionarioForm
from ..services import funcionario_service


@user_passes_test(lambda u: u.cargo == 2)
def listar_funcionarios(request):
    funcionarios = funcionario_service.listar_funcionarios()
    return render(request, 'funcionarios/lista_funcionarios.html', {'funcionarios': funcionarios})


@user_passes_test(lambda u: u.cargo == 2)
def inserir_funcionario(request):
    if request.method == "POST":
        form_funcionario = FuncionarioForm(request.POST)
        if form_funcionario.is_valid():
            nome = form_funcionario.cleaned_data["nome"]
            nascimento = form_funcionario.cleaned_data["nascimento"]
            cargo = form_funcionario.cleaned_data["cargo"]
            username = form_funcionario.cleaned_data["username"]
            password = make_password(
                form_funcionario.cleaned_data["password1"])
            funcionario_novo = funcionario.Funcionario(
                nome=nome, nascimento=nascimento, cargo=cargo, username=username, password=password)
            funcionario_service.cadastrar_funcionario(funcionario_novo)
            return redirect('listar_funcionarios')
    else:
        form_funcionario = FuncionarioForm()
    return render(request, 'funcionarios/form_funcionario.html', {'form_funcionario': form_funcionario})

app/templates/funcionarios/form_funcionario.html
{% extends "base.html" %}
{% load meus_filtros %}
{% block title %}
Cadastro de funcionários
{% endblock title %}

{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Cadastro de funcionários</h3>
    </div>
    <div class="box-body">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form_funcionario.nome.errors }}
                <label>Nome: </label>
                {{ form_funcionario.nome|addclass:'form-control' }}

            </div>

            <div class="form-group">
                {{ form_funcionario.nascimento.errors }}
                <label>Data de nascimento: </label>
                {{ form_funcionario.nascimento|addclass:'form-control' }}
            </div>

            <div class="form-group">
                {{ form_funcionario.cargo.errors }}
                <label>Cargo: </label>
                {{ form_funcionario.cargo|addclass:'form-control' }}
            </div>

            <hr>

            <div class="form-group">
                {{ form_funcionario.username.errors }}
                <label>Nome de usuário: </label>
                {{ form_funcionario.username|addclass:'form-control' }}
            </div>

            <div class="form-group">
                {{ form_funcionario.password1.errors }}
                <label>Senha: </label>
                {{ form_funcionario.password1|addclass:'form-control' }}
            </div>

            <div class="form-group">
                {{ form_funcionario.password2.errors }}
                <label>Confirmação de senha: </label>
                {{ form_funcionario.password2|addclass:'form-control' }}
            </div>

            <div class="form-group">
                <input type="submit" name="Cadastrar" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
{% endblock content %}

app/templates/funcionarios/lista_funcionarios.html
{% extends "base.html" %}

{% block title %}
Listagem de clientes
{% endblock title %}

{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Listagem de funcionários</h3>
    </div>
    <div class="box-body">
        <table class="table">
            <thead>
            <tr>
                <th>Nome</th>
                <th>Data de Nascimento</th>
                <th>Cargo</th>
                <th>User</th>
            </tr>
            </thead>
            <tbody>
            {% for i in funcionarios %}
            <tr>
                <td>{{i.nome}}</td>
                <td>{{i.nascimento}}</td>
                <td>{{i.get_cargo_display}}</td>
                <td>{{i.username}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <hr>

        <a href="{% url 'cadastrar_funcionario' %}">
            <button class="btn btn-primary">Cadastrar</button>
        </a>
    </div>
</div>
{% endblock content %}